### ISSUE TITLE
App breaks when using DB translation loaders in tests

### ISSUE THREAD

**Issue by LucaPuddu** [BenSampo/laravel-enum#245] opened 2022-02-08 01:24 UTC
Whenever a translation is used in the [service provider](https://github.com/BenSampo/laravel-enum/blob/master/src/EnumServiceProvider.php#L60), an app that loads translations from the DB (e.g. using [spatie/laravel-translation-loader](https://github.com/spatie/laravel-translation-loader)) will break, cause the database hasn't been migrated yet when the app is bootstrapped.

Steps:
1. install both packages without migrating the db
2. add a `/test` route:
    ```php
    Route::get('test', function () {
        return 'hello';
    });
    ```
3. go to `/test`
    ```
    Illuminate\Database\QueryException
    SQLSTATE[42S02]: Base table or view not found: 1146 Table 'homestead.language_lines' doesn't exist (SQL: select * from `language_lines` where `group` = *) 
    ```

Normally this is not an issue, because you should have the `language_lines` table in the db, but it totally breaks testing.

**Comment by alexandrmazur96** [comment] 2022-12-06 12:51
I can confirm that this behavior totally breaks our CI in compose with [brackets/craftable](https://github.com/BRACKETS-by-TRIAD/craftable).

This behavior will break CI with any other translation mechanism that requires DB connections (because we don't have filled DB before calling migrations that could not be called because of an error).

**Comment by alexandrmazur96** [comment] 2022-12-06 14:54
@spawnia 

> Do you think https://github.com/BenSampo/laravel-enum/pull/260 solves this issue adequately?

I tested it, and yes, [this PR](https://github.com/BenSampo/laravel-enum/pull/260) is fixing an issue.

**Comment by alexandrmazur96** [comment] 2022-12-06 15:44
If someone needs a workaround for this issue, you could do the following:

Firstly, add `bensampo/laravel-enum` to the dont-discover composer.json config: 

```composer config --merge extra.laravel.dont-discover --json '["bensampo/laravel-enum"]' ```

And after that, you could extend `BenSampo\Enum\EnumServiceProvider` and overwrite it with the code from PR:

```php
<?php

declare(strict_types=1);

namespace App\Providers;

use BenSampo\Enum\Commands\EnumAnnotateCommand;
use BenSampo\Enum\Commands\MakeEnumCommand;
use BenSampo\Enum\EnumServiceProvider as BaseEnumServiceProvider;
use BenSampo\Enum\EnumType;
use BenSampo\Enum\Rules\Enum;
use BenSampo\Enum\Rules\EnumKey;
use BenSampo\Enum\Rules\EnumValue;

/**
 * This is the temporary decision to make CI work.
 * Should be reverted after this PR https://github.com/BenSampo/laravel-enum/pull/260 is merged and released.
 */
final class EnumServiceProvider extends BaseEnumServiceProvider
{
    /**
     * Perform post-registration booting of services.
     */
    public function boot(): void
    {
        $this->bootCommands();
        $this->bootValidationTranslation();
        $this->bootValidators();
        $this->bootDoctrineType();
    }

    private function bootCommands(): void
    {
        $this->publishes([
            __DIR__ . '/Commands/stubs' => $this->app->basePath('stubs'),
        ], 'stubs');

        if ($this->app->runningInConsole()) {
            $this->commands([
                EnumAnnotateCommand::class,
                MakeEnumCommand::class,
            ]);
        }
    }

    private function bootValidators(): void
    {
        $this->app['validator']->extend('enum_key', function ($attribute, $value, $parameters, $validator) {
            $enum = $parameters[0] ?? '';

            return (new EnumKey($enum))->passes($attribute, $value);
        });

        $this->app['validator']->extend('enum_value', function ($attribute, $value, $parameters, $validator) {
            $enum = $parameters[0] ?? '';

            $strict = $parameters[1] ?? null;

            if (!$strict) {
                return (new EnumValue($enum))->passes($attribute, $value);
            }

            $strict = !!json_decode(strtolower($strict));

            return (new EnumValue($enum, $strict))->passes($attribute, $value);
        });

        $this->app['validator']->extend('enum', function ($attribute, $value, $parameters, $validator) {
            $enum = $parameters[0] ?? '';

            return (new Enum($enum))->passes($attribute, $value);
        });
    }

    private function bootDoctrineType(): void
    {
        // Not included by default in Laravel
        if (class_exists('Doctrine\DBAL\Types\Type')) {
            if (!Type::hasType(EnumType::ENUM)) {
                Type::addType(EnumType::ENUM, EnumType::class);
            }
        }
    }

    private function bootValidationTranslation(): void
    {
        $this->publishes([
            __DIR__ . '/../lang' => lang_path('vendor/laravelEnum'),
        ], 'translations');

        $this->loadTranslationsFrom(__DIR__ . '/../lang/', 'laravelEnum');
    }
}
```

You can't overwrite the `private` method, so... this is a little bit ugly, but it works.

**Comment by spawnia** [comment] 2022-12-07 09:50
> You can't overwrite the private method, so... this is a little bit ugly, but it works.

Please review https://github.com/BenSampo/laravel-enum/pull/292.

**Comment by spawnia** [comment] 2022-12-07 09:54
How about we switch to an entirely new approch to register validation rules - using [validation rule objects](https://laravel.com/docs/9.x/validation#using-rule-objects)?

See https://github.com/spatie/laravel-validation-rules for an example package that does this, including translations.

**Comment by spawnia** [comment] 2023-07-05 08:20
Fixed with https://github.com/BenSampo/laravel-enum/releases/tag/v6.4.0.

**Closed by spawnia** 2023-07-05 08:20 UTC
Labels: bug
