### ISSUE TITLE
Validating empty string throws an error

### ISSUE THREAD

**Issue by samiheikki** [BenSampo/laravel-enum#266] opened 2022-04-25 09:49 UTC
Validation file:
```
'event_type' => new EnumKey(EventType::class),
```

EventType.php
```
final class EventType extends Enum
{
    public const EVENT = 1;

    public const SEMINAR = 2;
}
```

Request:
```
{
  'event_type': '',
}
```

Expected result:
Validation returns error 422.

Actual result:
Validation returns error 500.

**Comment by spawnia** [comment] 2022-04-25 09:50
Do you have a stacktrace?

**Comment by samiheikki** [comment] 2022-04-25 10:04
> Do you have a stacktrace?

I do not.

**Comment by spawnia** [comment] 2022-07-11 10:28
Closing due to lack of detailed information or reproducible test.

**Closed by spawnia** 2022-07-11 10:28 UTC
